# Generated by Django 6.0 on 2026-01-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł gry')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Wydawca')),
                ('description', models.TextField(verbose_name='Opis gry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='market.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Gra planszowa',
                'verbose_name_plural': 'Gry planszowe',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (PLN)')),
                ('condition', models.CharField(choices=[('new', 'Nowa (w folii)'), ('used_good', 'Używana (stan bdb)'), ('used_poor', 'Używana (widoczne ślady)')], default='used_good', max_length=20, verbose_name='Stan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_photos/', verbose_name='Zdjęcie')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Sprzedane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='market.boardgame', verbose_name='Gra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sprzedający')),
            ],
            options={
                'verbose_name': 'Oferta sprzedaży',
                'verbose_name_plural': 'Oferty sprzedaży',
            },
        ),
    ]
